#################################
# PostgreSQL Container          #
#################################

db:
    image: postgres
    #volumes:
    #    - data:/usr/src/data
    expose:
        - "5432"

#################################
# Flask Container               #
#################################

web:
    build: ./web
    volumes:
        - web:/code
        - data:/data
    ports:
        - "80:5000"
    links: 
       - db:db
    working_dir: /code
    command: python app.py
